---

- name:  Create /dev directory in chroot
  file:
    path:  "{{ unbound_directory }}/dev/"
    state: directory

- name: Touch file for chroot'ed /dev/log
  shell: touch "{{ unbound_directory }}/dev/log"
  args:
    creates: "{{ unbound_directory }}/dev/log"

- name: Bind mount /dev/log
  mount:
    name:   "{{ unbound_directory }}/dev/log"
    src:    /dev/log
    fstype: none
    opts:   rw,bind
    state:  present

- name: Touch file for chroot'ed /dev/random
  shell: touch "{{ unbound_directory }}/dev/random"
  args:
    creates: "{{ unbound_directory }}/dev/random"

- name: Bind mount /dev/random
  mount:
    name:   "{{ unbound_directory }}/dev/random"
    src:    /dev/random
    fstype: none
    opts:   ro,bind
    state:  present
