---

- name: Install Unbound and role deps
  package:
    name:  '{{ item }}'
    state: installed
  with_items:
    - unbound

- name: Add Unbound server configuration
  template:
    src:  unbound.conf.j2
    dest: "{{ unbound_directory }}/unbound.conf"
  notify: restart unbound

- name: Add root hints
  copy:
    content: '{{ unbound_root_hints.content }}'
    dest:    '{{ unbound_root_hints.path }}'
    mode:  0644
    owner: root
    group: root
  when:
    - unbound_root_hints is defined

- name: Add includes
  copy:
    content: '{{ item.content }}'
    dest:    '{{ item.path }}'
    mode:  0644
    owner: root
    group: root
  with_items:
    - '{{ unbound_includes }}'

- name: Configure chroot
  include: chroot.yml

- name: Start and enable Unbound
  service:
    name:    unbound
    state:   started
    enabled: yes
