---

- name: Install Unbound and role deps
  package:
    name:  '{{ item }}'
    state: installed
  with_items:
    - unbound

- name: Add Unbound server configuration
  template:
    src:  unbound.conf.j2
    dest: "{{ unbound_directory }}/unbound.conf"
  notify: restart unbound

- name: Configure chroot
  include: chroot.yml

- name: Start and enable Unbound
  service:
    name:    unbound
    state:   started
    enabled: yes
